{% set version = '0.1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rolocisccnbs
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rolocISCCNBS_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rolocISCCNBS/rolocISCCNBS_{{ version }}.tar.gz
  sha256: 5595ffbf4fe92f3279c59e3b6a1e90a1ff7648149e343e1e2ff707266a811280

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-colorspace
    - r-roloc
  run:
    - r-base
    - r-colorspace
    - r-roloc

test:
  commands:
    - $R -e "library('rolocISCCNBS')"           # [not win]
    - "\"%R%\" -e \"library('rolocISCCNBS')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=rolocISCCNBS
  license: GPL-2.0-or-later
  summary: A colour list and colour metric based on the ISCC-NBS System of Color Designation
    for use with the 'roloc' package for converting colour specifications to colour
    names.
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - thewchan

# Package: rolocISCCNBS
# Type: Package
# Title: A Colour List and Colour Metric Based on the ISCC-NBS System of Color Designation
# Version: 0.1
# Author: Paul Murrell
# Maintainer: Paul Murrell <paul@stat.auckland.ac.nz>
# Description: A colour list and colour metric based on the ISCC-NBS System of Color Designation for use with the 'roloc' package for converting colour specifications to colour names.
# License: GPL-2 | GPL-3
# Depends: roloc
# Imports: methods, colorspace
# NeedsCompilation: no
# Packaged: 2018-07-30 21:15:35 UTC; pmur002
# Repository: CRAN
# Date/Publication: 2018-08-02 15:30:06 UTC
